### ISSUE TITLE
[BUG] 추가된 목소리 중 SSML 지원하지 않는 음성 존재

### ISSUE THREAD

**Issue by ja7811** [umc-owncast/OwnCast_backend#26]
8/1일 회의하면서 언어 별로 목소리 12개씩 확정지었는데...
SSML input을 지원하지 않는 목소리가 몇 개 있습니다
요걸로 요청하면 `"This voice currently does not support SSML input. Please try again with text only input."`라고 응답함
(TTS까진 지원되지만, SSML 태그가 지원 안되는 걸로 보임)

**지원 안되는 음성 목록**
- en-US-Journey-F
- en-US-Journey-D
- en-US-Studio-Q
- 확인 중.. 아마 더 있을 거임

지원 되는 음성만 따로 확인할 수 있으면 코멘트 남겨주세요

**API 참고**
https://cloud.google.com/text-to-speech/docs/ssml?hl=ko#select_a_voice

*(추가)
스크립트에 타임라인 넣으려면 SSML 외에도 
TTS 오디오를 다시 STT 돌리는 방법도 있더라구요 (STT API로 문장마다 타임스탬프 알 수 있음)
구글 API 대신 이거 쓰는 것도 방법인듯*

**Comment by yuuddin** [comment]
넹 pm님께 수정 목록 전달 받았습니당

**Comment by ja7811** [comment]
목소리 목록 확정했으므로 이슈 닫을게욥
