### ISSUE TITLE
캐스트 생성 중 TTS API 오류 (Sentence Too Long)

### ISSUE THREAD

**Issue by ja7811** [umc-owncast/OwnCast_backend#59]
# 😱 문제상황
화요일 회의 때 까지는 문제 없던 TTS API가.. 갑자기 말썽을 일으킵니다
캐스트 생성 과정은 아래와 같습니다
- keyword로 생성 : 프롬프트 생성 -> 스크립트 생성 (챗gpt) -> 문장 별 파싱 -> TTS 요청 -> 한국어로 번역 -> `List<Sentence>`로 모아서 return
- script로 생성 : 문장 별 파싱 -> TTS 요청 -> 한국어로 번역 -> `List<Sentence>`로 모아서 return

## 에러 위치 / 내용
스크립트 생성까지는 잘 되는데, TTS 요청(`TTSService::requestSpeech`)에서 API 오류를 던지네요
에러 내용은 다음과 같습니다

**1.** 
```{
  "isSuccess": false,
  "code": "COMMON500",
  "message": "서버 에러, 관리자에게 문의 바랍니다.",
  "result": "400 : \"{<EOL>  \"error\": {<EOL>    \"code\": 400,<EOL>    
  \"message\": \"This request contains sentences that are too long. Consider splitting up long sentences with sentence ending punctuation e.g. periods. Also consider removing SSML sentence tags (e.g. '\\u003cs\\u003e') as they can confuse Cloud Text-to-Speech.\",<EOL>    
  \"status\": \"INVALID_ARGUMENT\"<EOL>  }<EOL>}<EOL>\""
}
```
**2.** 
```{
  "isSuccess": false,
  "code": "COMMON500",
  "message": "서버 에러, 관리자에게 문의 바랍니다.",
  "result": "400 : \"{<EOL>  \"error\": {<EOL>    \"code\": 400,<EOL>    \"message\": \"Some sentences generate audio that is too long. Consider splitting up long sentences with sentence breaking punctuation (e.g. periods), and/or removing SSML \\u003cbreak\\u003e tags.\",<EOL>    \"status\": \"INVALID_ARGUMENT\"<EOL>  }<EOL>}<EOL>\""
}
```

보시면 **문장 길이가 너무 길다**는 내용의 오류를 던지는 걸 볼 수 있습니다

## 에러 나는 이유
이걸 아직 모르겠어요
스크립트 생성하는 방식은 동일해서 갑자기 에러날 이유가 없는데 왜 뜨는지 모르겠음..

대충 에러 이유를 짐작해보자면

**1. 실제로 문장이 너무 길다?**
- 지금까지 캐스트를 몇 개를 만들었는데.. 이걸로 걸릴 거였으면 진작에 걸렸어야 함

**2. 요청 할당량을 초과했다?**
- 분 당 요청 수 초과 : 분 당 1000개까지 허용이므로 그럴 가능성 X
- 요청 당 바이트 수 초과 : 5000바이트 까지 허용이라고 적혀있는 걸 봤는데, 그 이하로 요청을 해도 (영어 1000자 이하) 동일한 오류 발생함

**3. 구글 쪽 문제?**
- 구글 쪽에서 API 업데이트하다가 버그가 났거나 (똑예전에 사례 있었던 걸로 암.. )
- 파싱 편의성을 위해 문장 마지막에 @를 붙이는데.. 여기서 오류가 났다?

아직 뭔지 모르겠네요
계속 건드려보면서 업데이트 해야할 듯 합니다

**Comment by ja7811** [comment]
다시 API 이것저것 날리고 있는데..
글자 수가  600자 정도 이내면 에러 없이 잘 진행 되네요
600자 아래면 웬만하면 문제 없는 거 같고 600~1000자 사이면 운 좋으면 에러 안 떠요 (ㅋㅋ;)
- 1분짜리 캐스트가 보통 700 글자를 넘기므로 keyword로 캐스트 생성하면 거의 다 이 에러가 뜹니다

바이트 수 초과일 수도 있긴 한데..
이게 문제가 맞다면 
1. 스크립트가 600~1000자 사이일 때 왜 어쩔 땐 되고 어쩔 땐 안되는지 
2. 예전에는 긴 캐스트도 잘만 만들어줬었는데 지금은 왜 안되는지
를 모르겠네요

**Comment by ja7811** [comment]
완성된 캐스트들 mp3 들어보는데 목소리가 마지막에 뭉개지네요??
문장을 안 끊고 줄줄 읽는 거 같은 느낌인데

**Comment by ja7811** [comment]
해결했습니다 🎉
`ParsingService` 업데이트하면서 스크립트 파싱할 때 . , ? ! 같은 구두점들 없애버렸던 게 버그 원인이었군요
구두점들 놔두도록 변경하니까 해결됐습니다

**Comment by yuuddin** [comment]
> 해결했습니다 🎉 `ParsingService` 업데이트하면서 스크립트 파싱할 때 . , ? ! 같은 구두점들 없애버렸던 게 버그 원인이었군요 구두점들 놔두도록 변경하니까 해결됐습니다

사실 구두점이 중요한게 아니고 \n으로 문장마다 줄바꿈을 해줌으로써 해결했습니다
구두점에서 아이디어 얻어서 작업하다가 발견했음...
