### ISSUE TITLE
서버 시작 시 카테고리 (메인/서브) 엔티티 DB에 자동 저장하는 기능

### ISSUE THREAD

**Issue by ja7811** [umc-owncast/OwnCast_backend#68]
메인 카테고리랑 서브카테고리 엔티티 저장하는 기능이 없어서
손수 넣고 있는 상황입니다

![세부카테고리](https://github.com/user-attachments/assets/00a365b9-94c4-4930-89b3-1eda03710956)
지정 카테고리는 서버 돌아가는 동안 테이블에 늘 저장돼있어야 해요
- 메인 카테고리: 드라마/영화, 스포츠, 음식, 등등 피그마에 소개된 것들
- 서브 카테고리: PM한테 세부 목록 물어봐야 함

## TODO
서버 실행할 때마다 지정 카테고리들 엔티티 저장됐는지 확인하고,
저장되지 않은 경우 해당 카테고리 저장해주는 기능

**구현 방법**
`ApplicationRunner`를 상속받아서 직접 구현한 후 `@Component`로 등록하면
서버 실행할 때 자동 실행되도록 만들 수 있습니다

손수 데이터를 집어넣어도 되긴 하는데..
- 카테고리가 많아지는 경우 실수할 가능성 (중간에 하나 빠뜨리거나)
- 로컬에서 돌리는 등의 이유로 DB가 달라지면, 매번 데이터를 손수 넣어줘야 함
- 누군가가 스키마 바꾸면서 ddl-auto create로 테이블 날린다면 손수 넣은 카테고리도 같이 날아감

등의 이유로 언젠가 만드는 게 좋지 않을까 싶습니다

**Comment by yuuddin** [comment]
음.. 기본 카테고리 저장 로직 확인 했습니다

추가로 사용자가 만드는 카테고리의 경우 해당 카테고리 저장해주는 기능은 이미 구현되어 있습니다

**Comment by yuuddin** [comment]
이거 그리고 추후 main category enum화 작업 진행할게요 
8개로 고정이라
