### ISSUE TITLE
Playlist 조회 API에서 Playlist 정보 포함해야함

### ISSUE THREAD

**Issue by ja7811** [umc-owncast/OwnCast_backend#72]
생성된 캐스트가 어느 카테고리에 속하는지 분석하는 작업이 필요합니다

![KakaoTalk_20240820_210341699](https://github.com/user-attachments/assets/aca3c873-336b-4c09-9b5b-efe5c071ae2e)

지금은 `List<Cast>`만 반환하고 있어서,,
플레이리스트명이랑 이미지 경로랑 이것저것 포함해줘야 해요

**Comment by YamYamee** [comment]
미션 완료~~

![image](https://github.com/user-attachments/assets/9c4d19a7-1ac3-4711-9708-87027b5d6d92)
