### ISSUE TITLE
ERD 관련 이슈

### ISSUE THREAD

**Issue by ja7811** [umc-owncast/OwnCast_backend#9]
![owncast_final](https://github.com/user-attachments/assets/c25ae0f4-a82d-4581-b675-a9e118e106cf)
저번에 만든 ERD에 문제가 조금 있어서 올립니다
만들 땐 몰랐는데 천천히 보니까 문제가 보이네요 🥲 
함 읽어보시고 댓글이던 카톡이던 의견 주세요

### 1. `member`와 `sub_category`를 잇는 테이블이 없음
말 그대로입니다.
`member`와 `main_category`는 `prefer` 테이블로 이어지지만 `member`와 `sub_category`는 이어주는 테이블이 없네요
해결방안은 두 개 정도 생각해봤습니다
- `member`와 `sub_category`를 잇는 테이블을 새로 만든다
   -> `member`와 `main_category`를 잇는 테이블은 `prefer`대신 `main_prefer` 정도로 바꾸고 
   새로운 테이블은 `sub_prefer` 정도로 이름 지으면 될 듯??
- `main_category`와 `sub_category`를 통합한다
  새로운 테이블 만드는 게 싫다면 카테고리를 통합해도 될 것 같습니다. 저번 회의 때 제가 말했던 방법입니다
- 일단 전자가 나아보이긴 해요

### 2. `cast`와 `main_category`를 잇는 테이블이 없음
이것도 말 그대로 입니다.
해결방안도 그대로 두 가지 입니다.
- `cast`와 `main_category`를 잇는 테이블을 새로 만든다
- `main_category`와 `sub_category`를 통일한다

### 3. `cast_like` 테이블
이거 왜 넣었는지 기억이 안남..
오늘 기능 훑어볼 땐 좋아요 기능이 없었던 거 같은데 왜 넣었었죠?? 🤔

**Comment by YamYamee** [comment]
3번은 wireframe에서 아래 사진처럼 좋아요 항목이 있어서 추가했던걸로 기억합니다.

![image](https://github.com/user-attachments/assets/4b820322-0a98-42bf-b13e-ea737f2cfcfe)

**Comment by ja7811** [comment]
### 3번
`cast_like` 테이블 삭제했습니다
추가적으로 `bookmark` 매핑 관련해서 의견 수렴해서 `sentence`와 `cast_playlist`를 매핑하는 걸로 변경했습니다

### 1, 2번
일단 둘 다 첫 번째 방식으로 (새로 테이블 만드는 방식) 변경했습니다

바뀐 ERD는 이렇게 됩니다
![owncast_final (1)](https://github.com/user-attachments/assets/d7cd4034-5f00-404a-a9d1-afb791e36d34)

**Comment by ja7811** [comment]
일단 이렇게 써보고 문제 생기면 바꾸는 방식으로 합시당 🙂
